_security:
    resource: "@VideothequeBundle/Controller/SecurityController.php"
    type:     annotation

# Cette route sera gérée automatiquement par symfony, il faut juste la déclarer
_security_login_check:
    path: /login_check

# Cette route sera gérée automatiquement par symfony, il faut juste la déclarer
_security_logout:
    path: /logout

_admin:
    resource: "@VideothequeBundle/Controller/AdminController.php"
    type:     annotation

_genre:
    resource: "@VideothequeBundle/Controller/GenreController.php"
    type:     annotation

_film:
    resource: "@VideothequeBundle/Controller/FilmController.php"
    type:     annotation

_default:
    resource: "@VideothequeBundle/Controller/DefaultController.php"
    type:     annotation